services:
  redis:
    image: redis:7-alpine
    container_name: n8n-redis
    restart: always
    networks:
      - n8n-net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: aws-1-ap-south-1.pooler.supabase.com
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_USER: postgres.skjwescceppmregjnwmg
      DB_POSTGRESDB_PASSWORD: zJ1aWrJOO3E5tVgl
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_SSL: "true"
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"

      # Core
      NODE_ENV: production
      N8N_ENCRYPTION_KEY: 2aebb6d396bdac2695ca8128e9a05254

      # âœ… External runners
      N8N_RUNNERS_MODE: external
      N8N_RUNNERS_AUTH_TOKEN: d733c07e718db5ecdedeb3571283faaf

      # Redis (REQUIRED)
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

    depends_on:
      - redis
    networks:
      - n8n-net

  n8n-runner:
    image: n8nio/runners:latest
    container_name: n8n-runner
    restart: always
    environment:
      N8N_RUNNERS_AUTH_TOKEN: d733c07e718db5ecdedeb3571283faaf
      N8N_RUNNERS_TASK_BROKER_URI: http://n8n:5679
      N8N_RUNNERS_ENABLE_PYTHON: "true"
      NODE_ENV: production
    depends_on:
      - n8n
    networks:
      - n8n-net

networks:
  n8n-net:
    driver: bridge
